Vagrant.configure("2") do |config|
    config.vm.define "client" do |client|
        client.vm.box = "generic/ubuntu2004"
        client.vm.hostname = "client"
        client.vm.network "private_network", ip: "10.10.20.3"
        
        client.vm.provider "libvirt" do |v|
            v.memory = 2048
            v.cpus = 1
        end
    end
end

