Vagrant.configure("2") do |config|
  config.vm.define "server" do |server|
    server.vm.box = "generic/ubuntu2004"
    server.vm.hostname = "server"
    server.vm.network "private_network", ip: "192.168.0.10"
    
    server.vm.provision "ansible" do |ansible|
      ansible.playbook = "fichier.yml"
    end

    server.vm.provider "libvirt" do |v|
      v.memory = 2048
      v.cpus = 1
    end
  end
end

